### ISSUE TITLE
improve display of space grid

### ISSUE THREAD

**Issue by juancarlosfarah** [graasp/graasp-desktop#108]
Fix the width of the cards. Then make it look better either by making the cards fit more snugly or by fixing the height and making the descriptions scrollable.

**Comment by pyphilia** [comment]
![image](https://user-images.githubusercontent.com/11229627/62163964-c6a98c80-b31b-11e9-941a-7a54ce9a185b.png)
I have something like this, the columns update depending on the window width and we have a trash icon which can also delete the space! I will work on the sync button tomorrow.

I feel like the "Play" button is too related to video content, don't you think? Maybe we should try the `arrow_foward` arrow?

I also noticed that when you open the menu, it will decrease the size of the content container. I think it would be more natural to make it come over the content instead of pushing it on the right side. For now it breaks slightly the layout when we open it.

**Comment by pyphilia** [comment]
![image](https://user-images.githubusercontent.com/11229627/62213831-20559980-b3a4-11e9-8b75-c08524e11a40.png)
I added all the buttons (export + sync) and I added a bit of responsive to have something nicer!

Some screenshots with different window sizes:
![image](https://user-images.githubusercontent.com/11229627/62214050-8c380200-b3a4-11e9-8248-c809243c633c.png)
![image](https://user-images.githubusercontent.com/11229627/62214070-96f29700-b3a4-11e9-954b-8741f6c597bd.png)
![image](https://user-images.githubusercontent.com/11229627/62214075-9b1eb480-b3a4-11e9-858d-9d4e6d3ddb4e.png)
![image](https://user-images.githubusercontent.com/11229627/62214113-aa056700-b3a4-11e9-809c-98aafd2531ec.png)

I think I am done with this issue, what do you think @juancarlosfarah ?
